apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tuto-cert
  namespace: default
spec:
  secretName: tuto-tls # Change to the secret name you want
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: tuto.freeboxos.fr # Change to your domain name
  dnsNames:
  - tuto.freeboxos.fr # Change to your domain name
